services:
  - type: web
    name: sportsgraph-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
