services:
  - type: web
    name: sportsgraph-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        fromService:
          type: web
          name: sportsgraph-frontend
          property: url
